name = "changhai-software"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_directory = "out"

[build.environment]
NODE_VERSION = "20"

[site]
bucket = "./out"
entry-point = "."

[env.production]
name = "changhai-software" 